//! The `win32k.sys` import surface: the ntoskrnl.exe entry points that the real
//! ReactOS `win32k.sys` (0.4.17) links against, plus the exact import name lists
//! used by the coverage test and by Phase 2's win32k component loader.
//!
//! win32k.sys imports **224** functions from `ntoskrnl.exe`, **1** from `hal.dll`
//! (`KeQueryPerformanceCounter`, in [`crate::hal`]), and **34** `FT_*` FreeType
//! functions from `ftfd.dll` (the font driver) — the FreeType imports have no
//! kernel dependency and are intentionally out of scope here (see
//! [`WIN32K_FTFD_IMPORTS`]).
//!
//! Each descriptor's [`ExportStatus`](crate::ExportStatus) reflects how it is
//! serviced: `Implemented`/`Partial` = wired to a real `nt-*` subsystem (or
//! implemented in [`crate::rtl`]/[`crate::ssdt`]); `StubSuccess`/`StubFailure` =
//! a thin stub with sane out-params (TODO Phase 2); `TrapIfCalled` = fail-loud
//! (logs + traps) for paths not reachable during win32k bring-up.

use crate::ExportStatus::*;
use crate::{ExportDescriptor, ExportStatus};

const fn e(name: &'static str, status: ExportStatus, notes: &'static str) -> ExportDescriptor {
    ExportDescriptor {
        dll: "ntoskrnl.exe",
        name,
        status,
        notes,
    }
}

/// The `ntoskrnl.exe` exports imported by `win32k.sys` that are **not** already
/// covered by the base [`crate::ntoskrnl::NTOSKRNL`] MVP table. Chained into the
/// registry alongside it.
pub const WIN32K_NTOSKRNL: &[ExportDescriptor] = &[
    // --- Mm ---
    e("MmMapViewInSystemSpace", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmUnmapViewInSessionSpace", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmUnmapViewInSystemSpace", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmCreateSection", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmMapViewOfSection", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmUnmapViewOfSection", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmUnsecureVirtualMemory", Partial, "VA secure/unsecure tracked by nt-address-space; returns an opaque handle"),
    e("MmSecureVirtualMemory", Partial, "VA secure/unsecure tracked by nt-address-space; returns an opaque handle"),
    e("MmSystemRangeStart", Partial, "data export: fixed x64 system/user address boundary constant"),
    e("MmPageEntireDriver", StubSuccess, "no demand paging of drivers on the host; returns the image base"),
    e("MmUserProbeAddress", Partial, "data export: fixed x64 system/user address boundary constant"),
    e("MmMapViewInSessionSpace", Partial, "section create/map routed to nt-memory-manager (system/session views share the host AS)"),
    e("MmHighestUserAddress", Partial, "data export: fixed x64 system/user address boundary constant"),
    // --- Ob ---
    e("ObfReferenceObject", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObCloseHandle", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObOpenObjectByPointer", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObCreateObject", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObOpenObjectByName", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObFindHandleForObject", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObGetObjectSecurity", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObReleaseObjectSecurity", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObAssignSecurity", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObReferenceObjectByPointer", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObInsertObject", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObReferenceObjectByHandle", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    e("ObfDereferenceObject", Partial, "object reference/handle/security ops routed to nt-object-manager"),
    // --- Ps ---
    e("PsGetThreadWin32Thread", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsGetProcessId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetProcessWin32Process", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsSetProcessWin32Process", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsSetThreadWin32Thread", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsEstablishWin32Callouts", Partial, "records win32k's WIN32_CALLOUTS table in nt-process (Win32Callouts); Phase 2 invokes them"),
    e("PsGetProcessExitStatus", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetCurrentThreadWin32Thread", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsGetCurrentProcessId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetCurrentThreadId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetCurrentProcessSessionId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsLookupThreadByThreadId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetThreadId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsLookupProcessByProcessId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsIsSystemProcess", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetThreadProcessId", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetProcessExitProcessCalled", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetThreadProcess", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsReferenceImpersonationToken", Partial, "token references routed to nt-security's token store"),
    e("PsIsThreadTerminating", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsReferencePrimaryToken", Partial, "token references routed to nt-security's token store"),
    e("PsGetThreadFreezeCount", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsIsSystemThread", Partial, "process/thread identity + state queries routed to nt-process"),
    e("PsGetProcessWin32WindowStation", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsSetProcessWindowStation", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsProcessType", Partial, "data export: EPROCESS/ETHREAD object-type pointer (nt-object-manager)"),
    e("PsGetCurrentProcessWin32Process", Partial, "Win32 per-process/thread context pointer-slot in nt-process (ProcessManager win32 accessors)"),
    e("PsThreadType", Partial, "data export: EPROCESS/ETHREAD object-type pointer (nt-object-manager)"),
    // --- Ke ---
    e("KeBugCheck", TrapIfCalled, "bugcheck: logs the code + panics (fail-loud)"),
    e("KeSetKernelStackSwapEnable", StubSuccess, "no kernel-stack swapping on the host; returns prior state"),
    e("KeAddSystemServiceTable", Partial, "records win32k's NtUser/NtGdi SSDT (base/count/table) in crate::ssdt for Phase 2 routing"),
    e("KeEnterCriticalRegion", Partial, "APC-disable nesting counter via nt-kernel-exec critical regions"),
    e("KeLeaveCriticalRegion", Partial, "APC-disable nesting counter via nt-kernel-exec critical regions"),
    e("KeUserModeCallback", TrapIfCalled, "user-mode callback needs the Phase 2 win32k<->client IPC path; traps until then"),
    e("KeAttachProcess", Partial, "process-context attach tracked by nt-process; single address space on the host"),
    e("KeDetachProcess", Partial, "process-context attach tracked by nt-process; single address space on the host"),
    e("KeStackAttachProcess", Partial, "process-context attach tracked by nt-process; single address space on the host"),
    e("KeInitializeTimer", Partial, "timer via nt-kernel-exec TimerQueue"),
    e("KeSetPriorityThread", StubSuccess, "records thread priority; host scheduler is cooperative"),
    e("KeWaitForMultipleObjects", Partial, "single-threaded host: satisfied-or-timeout wait via nt-kernel-exec; no real block"),
    e("KeBugCheckEx", TrapIfCalled, "bugcheck: logs the code + panics (fail-loud)"),
    e("KeIsAttachedProcess", Partial, "process-context attach tracked by nt-process; single address space on the host"),
    e("KeSetTimer", Partial, "timer via nt-kernel-exec TimerQueue"),
    e("KePulseEvent", Partial, "event state via nt-kernel-exec EventStore"),
    e("KeWaitForSingleObject", Partial, "single-threaded host: satisfied-or-timeout wait via nt-kernel-exec; no real block"),
    e("KeReadStateEvent", Partial, "event state via nt-kernel-exec EventStore"),
    e("KeUnstackDetachProcess", Partial, "process-context attach tracked by nt-process; single address space on the host"),
    // --- Ex ---
    e("ExDeleteResourceLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExInitializeResourceLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExIsResourceAcquiredExclusiveLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExEnterCriticalRegionAndAcquireResourceShared", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExEnterCriticalRegionAndAcquireResourceExclusive", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExReleaseResourceAndLeaveCriticalRegion", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExGetPreviousMode", StubSuccess, "returns the caller's previous mode (UserMode for win32k syscalls)"),
    e("ExAcquireResourceExclusiveLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExReleaseResourceLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExRaiseAccessViolation", TrapIfCalled, "raises a structured exception; not modelled on the host, traps if reached"),
    e("ExDesktopObjectType", Partial, "data export: object-type pointer (nt-object-manager)"),
    e("ExWindowStationObjectType", Partial, "data export: object-type pointer (nt-object-manager)"),
    e("ExRaiseStatus", TrapIfCalled, "raises a structured exception; not modelled on the host, traps if reached"),
    e("ExpInterlockedPushEntrySList", Partial, "SLIST push/pop/depth over an alloc-backed stack"),
    e("ExpInterlockedPopEntrySList", Partial, "SLIST push/pop/depth over an alloc-backed stack"),
    e("ExQueryDepthSList", Partial, "SLIST push/pop/depth over an alloc-backed stack"),
    e("ExInitializePagedLookasideList", StubSuccess, "lookaside falls back to the pool arena"),
    e("ExAcquireResourceSharedLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExIsResourceAcquiredSharedLite", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExAcquireFastMutexUnsafe", Partial, "fast-mutex ownership counter via nt-kernel-exec"),
    e("ExReleaseFastMutexUnsafe", Partial, "fast-mutex ownership counter via nt-kernel-exec"),
    e("ExEnterCriticalRegionAndAcquireFastMutexUnsafe", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExReleaseFastMutexUnsafeAndLeaveCriticalRegion", Partial, "ERESOURCE reader/writer + critical-region ops via nt-kernel-exec (single-threaded)"),
    e("ExAllocatePoolWithQuotaTag", Partial, "pool alloc routed to the Driver Host arena (quota/tag ignored)"),
    e("ExfAcquirePushLockExclusive", StubSuccess, "push-lock is a no-op on the single-threaded host"),
    e("ExfTryToWakePushLock", StubSuccess, "push-lock is a no-op on the single-threaded host"),
    e("ExAllocatePool", Partial, "pool alloc routed to the Driver Host arena (quota/tag ignored)"),
    e("ExSystemTimeToLocalTime", StubSuccess, "applies a zero bias (UTC==local on the host)"),
    e("ExEventObjectType", Partial, "data export: object-type pointer (nt-object-manager)"),
    // --- Zw ---
    e("ZwAllocateVirtualMemory", Partial, "virtual-memory/section ops routed to nt-memory-manager/nt-address-space"),
    e("ZwFreeVirtualMemory", Partial, "virtual-memory/section ops routed to nt-memory-manager/nt-address-space"),
    e("ZwCreateEvent", Partial, "event object routed to nt-kernel-exec + nt-object-manager"),
    e("ZwCreateSection", Partial, "virtual-memory/section ops routed to nt-memory-manager/nt-address-space"),
    e("ZwCreateKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwDeleteValueKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwEnumerateValueKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwOpenKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwQueryValueKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwSetValueKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwDuplicateObject", Partial, "handle/directory-object ops routed to nt-object-manager"),
    e("ZwOpenFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwReadFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwCancelIoFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwQueryDefaultLocale", StubSuccess, "returns the system default LCID"),
    e("ZwDeviceIoControlFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwYieldExecution", StubSuccess, "cooperative yield: no-op returning STATUS_SUCCESS"),
    e("ZwQueryInformationToken", Partial, "token open/query routed to nt-security"),
    e("ZwOpenThreadToken", Partial, "token open/query routed to nt-security"),
    e("ZwOpenProcessToken", Partial, "token open/query routed to nt-security"),
    e("ZwCreateDirectoryObject", Partial, "handle/directory-object ops routed to nt-object-manager"),
    e("ZwOpenDirectoryObject", Partial, "handle/directory-object ops routed to nt-object-manager"),
    e("ZwQueryDirectoryObject", Partial, "handle/directory-object ops routed to nt-object-manager"),
    e("ZwQuerySystemInformation", StubSuccess, "system-information classes win32k needs return canned values; TODO Phase 2"),
    e("ZwQueryKey", Partial, "registry ops routed to nt-config-manager"),
    e("ZwQueryObject", Partial, "handle/directory-object ops routed to nt-object-manager"),
    e("ZwQueryDirectoryFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwQueryInformationFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwUnmapViewOfSection", Partial, "virtual-memory/section ops routed to nt-memory-manager/nt-address-space"),
    e("ZwMapViewOfSection", Partial, "virtual-memory/section ops routed to nt-memory-manager/nt-address-space"),
    e("ZwCreateFile", StubSuccess, "file ops routed to nt-fs where mounted; else success with empty result (Phase 2 wiring)"),
    e("ZwSetSystemInformation", StubSuccess, "system-information classes win32k needs return canned values; TODO Phase 2"),
    e("ZwClose", Partial, "handle/directory-object ops routed to nt-object-manager"),
    // --- Rtl ---
    e("RtlGetDefaultCodePage", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlAllocateHeap", Partial, "heap ops routed to the Driver Host pool arena; no per-heap accounting"),
    e("RtlAnsiStringToUnicodeString", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlInitAnsiString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlCreateUnicodeString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlFreeUnicodeString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlAppendUnicodeStringToString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlFormatCurrentUserKeyPath", Partial, "returns the \\Registry\\User\\<sid> path for the current subject"),
    e("RtlMultiByteToUnicodeN", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlUnicodeStringToAnsiString", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlxUnicodeStringToAnsiSize", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlFreeHeap", Partial, "heap ops routed to the Driver Host pool arena; no per-heap accounting"),
    e("RtlAddAtomToAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlDeleteAtomFromAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlQueryAtomInAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlLookupAtomInAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlUnicodeToMultiByteSize", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlGetVersion", StubSuccess, "returns a fixed RTL_OSVERSIONINFOW (NT 5.2 / ReactOS)"),
    e("RtlCompareMemory", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlOemToUnicodeN", Partial, "codepage conversion backed by the loaded NLS tables (c_1252/c_437/l_intl)"),
    e("RtlIntegerToUnicodeString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlUnicodeStringToInteger", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlSizeHeap", Partial, "heap ops routed to the Driver Host pool arena; no per-heap accounting"),
    e("RtlCreateSecurityDescriptor", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlSetDaclSecurityDescriptor", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlLengthSid", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlCreateAcl", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlAddAccessAllowedAceEx", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlSetOwnerSecurityDescriptor", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlSetGroupSecurityDescriptor", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlAbsoluteToSelfRelativeSD", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlCreateAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlAreAllAccessesGranted", Partial, "security-descriptor/ACL/SID helpers routed to nt-security"),
    e("RtlClearAllBits", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlFindClearBitsAndSet", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlInitializeBitMap", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlClearBit", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlPinAtomInAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlCreateHeap", Partial, "heap ops routed to the Driver Host pool arena; no per-heap accounting"),
    e("RtlDestroyAtomTable", Partial, "atom table over an alloc-backed map; used by win32k for window-class atoms"),
    e("RtlImageNtHeader", Partial, "PE header/data-directory parsing routed to nt-pe-loader"),
    e("RtlNumberOfSetBits", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlTestBit", Partial, "RTL_BITMAP ops over the caller's buffer"),
    e("RtlTimeToTimeFields", StubSuccess, "splits a 100ns time into TIME_FIELDS"),
    e("RtlUnwindEx", TrapIfCalled, "structured-exception unwind not modelled on the host; traps if reached"),
    e("RtlUpcaseUnicodeChar", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlAnsiCharToUnicodeChar", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlImageDirectoryEntryToData", Partial, "PE header/data-directory parsing routed to nt-pe-loader"),
    e("RtlAppendUnicodeToString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    e("RtlNtStatusToDosError", Partial, "status->Win32 error mapping (common subset)"),
    e("RtlQueryRegistryValues", StubSuccess, "registry query table walked against nt-config; returns success with defaults"),
    e("RtlEqualUnicodeString", Implemented, "implemented in crate::rtl (host-tested UNICODE_STRING/string ops)"),
    // --- Io ---
    e("IoGetDeviceProperty", StubSuccess, "returns benign device-property/stack-limit values for win32k init"),
    e("IoGetStackLimits", StubSuccess, "returns benign device-property/stack-limit values for win32k init"),
    e("IoGetCurrentProcess", Partial, "returns the current EPROCESS via nt-process"),
    e("IoSynchronousInvalidateDeviceRelations", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    e("IoOpenDeviceRegistryKey", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    e("IoGetRelatedDeviceObject", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    e("IoGetDeviceObjectPointer", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    e("IofCallDriver", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    e("IoBuildSynchronousFsdRequest", TrapIfCalled, "device-stack I/O not reached on the win32k init path; traps if called"),
    // --- Se ---
    e("SeQueryAuthenticationIdToken", Partial, "subject-context/privilege checks routed to nt-security"),
    e("SeExports", Partial, "data export: the SE_EXPORTS well-known-SID/privilege table"),
    e("SeReleaseSubjectContext", Partial, "subject-context/privilege checks routed to nt-security"),
    e("SeUnlockSubjectContext", Partial, "subject-context/privilege checks routed to nt-security"),
    e("SeCaptureSubjectContext", Partial, "subject-context/privilege checks routed to nt-security"),
    e("SeLockSubjectContext", Partial, "subject-context/privilege checks routed to nt-security"),
    e("SePrivilegeCheck", Partial, "subject-context/privilege checks routed to nt-security"),
    // --- Lpc ---
    e("LpcRequestWaitReplyPort", TrapIfCalled, "LPC ports are Phase 4; traps until the port layer exists"),
    e("LpcRequestPort", TrapIfCalled, "LPC ports are Phase 4; traps until the port layer exists"),
    e("LpcPortObjectType", Partial, "data export: LPC port object-type pointer"),
    // --- Probe ---
    e("ProbeForWrite", Partial, "user-buffer bounds check against MmUserProbeAddress"),
    e("ProbeForRead", Partial, "user-buffer bounds check against MmUserProbeAddress"),
    // --- Nt ---
    e("NtQuerySystemInformation", StubSuccess, "system-information classes return canned values"),
    e("NtAddAtom", Partial, "global atom add routed to the Rtl atom table"),
    // --- Po ---
    e("PoRequestShutdownEvent", StubSuccess, "records a shutdown-event request; never signalled on the host"),
    // --- vDbg ---
    e("vDbgPrintExWithPrefix", Partial, "va_list DbgPrint variant; same format limits as DbgPrint"),
    // --- Nls ---
    e("NlsMbCodePageTag", Partial, "data export: multibyte-codepage flag from the loaded NLS tables"),
];

pub const WIN32K_NTOSKRNL_IMPORTS: &[&str] = &[
    "MmMapViewInSystemSpace",
    "MmUnmapViewInSessionSpace",
    "MmUnmapViewInSystemSpace",
    "MmCreateSection",
    "MmMapViewOfSection",
    "MmUnmapViewOfSection",
    "ProbeForWrite",
    "MmUnsecureVirtualMemory",
    "MmSecureVirtualMemory",
    "ZwAllocateVirtualMemory",
    "ZwFreeVirtualMemory",
    "NtQuerySystemInformation",
    "RtlGetDefaultCodePage",
    "MmSystemRangeStart",
    "ExDeleteResourceLite",
    "ExInitializeResourceLite",
    "ExIsResourceAcquiredExclusiveLite",
    "ExEnterCriticalRegionAndAcquireResourceShared",
    "ExEnterCriticalRegionAndAcquireResourceExclusive",
    "ExReleaseResourceAndLeaveCriticalRegion",
    "PsGetThreadWin32Thread",
    "MmPageEntireDriver",
    "ObfReferenceObject",
    "KeBugCheck",
    "PsGetProcessId",
    "RtlAllocateHeap",
    "KeSetKernelStackSwapEnable",
    "ZwCreateEvent",
    "KeAddSystemServiceTable",
    "ObCloseHandle",
    "PsGetProcessWin32Process",
    "PsSetProcessWin32Process",
    "PsSetThreadWin32Thread",
    "PsEstablishWin32Callouts",
    "PsGetProcessExitStatus",
    "ZwCreateSection",
    "RtlAnsiStringToUnicodeString",
    "RtlInitAnsiString",
    "RtlCreateUnicodeString",
    "ExGetPreviousMode",
    "RtlFreeUnicodeString",
    "RtlAppendUnicodeStringToString",
    "ZwCreateKey",
    "ZwDeleteValueKey",
    "ZwEnumerateValueKey",
    "ZwOpenKey",
    "ZwQueryValueKey",
    "ZwSetValueKey",
    "RtlFormatCurrentUserKeyPath",
    "KeEnterCriticalRegion",
    "KeLeaveCriticalRegion",
    "ExAcquireResourceExclusiveLite",
    "ExReleaseResourceLite",
    "RtlMultiByteToUnicodeN",
    "PsGetCurrentThreadWin32Thread",
    "KeUserModeCallback",
    "RtlUnicodeStringToAnsiString",
    "RtlxUnicodeStringToAnsiSize",
    "ExRaiseAccessViolation",
    "RtlFreeHeap",
    "RtlAddAtomToAtomTable",
    "RtlDeleteAtomFromAtomTable",
    "RtlQueryAtomInAtomTable",
    "RtlLookupAtomInAtomTable",
    "MmUserProbeAddress",
    "ExDesktopObjectType",
    "LpcRequestWaitReplyPort",
    "LpcRequestPort",
    "LpcPortObjectType",
    "RtlCompareUnicodeString",
    "RtlUnicodeToMultiByteSize",
    "RtlGetVersion",
    "PsGetCurrentProcessId",
    "PsGetCurrentThreadId",
    "KeAttachProcess",
    "KeDetachProcess",
    "ObOpenObjectByPointer",
    "ZwDuplicateObject",
    "ObCreateObject",
    "ObOpenObjectByName",
    "ObFindHandleForObject",
    "PsGetCurrentProcessSessionId",
    "ExWindowStationObjectType",
    "RtlCompareMemory",
    "IoGetDeviceProperty",
    "ExRaiseStatus",
    "PsLookupThreadByThreadId",
    "PsGetThreadId",
    "PsLookupProcessByProcessId",
    "KeStackAttachProcess",
    "MmMapViewInSessionSpace",
    "PsIsSystemProcess",
    "KeInitializeTimer",
    "KeSetPriorityThread",
    "KeWaitForMultipleObjects",
    "PoRequestShutdownEvent",
    "ZwOpenFile",
    "ZwReadFile",
    "ZwCancelIoFile",
    "PsGetThreadProcessId",
    "ZwQueryDefaultLocale",
    "ZwDeviceIoControlFile",
    "RtlOemToUnicodeN",
    "RtlIntegerToUnicodeString",
    "RtlUnicodeStringToInteger",
    "RtlSizeHeap",
    "IoGetStackLimits",
    "ZwYieldExecution",
    "PsGetProcessExitProcessCalled",
    "PsGetThreadProcess",
    "SeQueryAuthenticationIdToken",
    "PsReferenceImpersonationToken",
    "PsIsThreadTerminating",
    "PsReferencePrimaryToken",
    "ExpInterlockedPushEntrySList",
    "ExpInterlockedPopEntrySList",
    "ExQueryDepthSList",
    "ExInitializePagedLookasideList",
    "PsGetThreadFreezeCount",
    "KeBugCheckEx",
    "ExAcquireResourceSharedLite",
    "ExIsResourceAcquiredSharedLite",
    "NtAddAtom",
    "ExAcquireFastMutexUnsafe",
    "ExReleaseFastMutexUnsafe",
    "PsIsSystemThread",
    "KeIsAttachedProcess",
    "RtlCreateSecurityDescriptor",
    "RtlSetDaclSecurityDescriptor",
    "ObGetObjectSecurity",
    "ObReleaseObjectSecurity",
    "RtlLengthSid",
    "RtlCreateAcl",
    "RtlAddAccessAllowedAceEx",
    "RtlSetOwnerSecurityDescriptor",
    "RtlSetGroupSecurityDescriptor",
    "RtlAbsoluteToSelfRelativeSD",
    "ZwQueryInformationToken",
    "ObAssignSecurity",
    "ZwOpenThreadToken",
    "ZwOpenProcessToken",
    "SeExports",
    "RtlCreateAtomTable",
    "SeReleaseSubjectContext",
    "SeUnlockSubjectContext",
    "SeCaptureSubjectContext",
    "SeLockSubjectContext",
    "SePrivilegeCheck",
    "RtlAreAllAccessesGranted",
    "KeSetTimer",
    "RtlClearAllBits",
    "RtlFindClearBitsAndSet",
    "RtlInitializeBitMap",
    "RtlClearBit",
    "ExEnterCriticalRegionAndAcquireFastMutexUnsafe",
    "ExReleaseFastMutexUnsafeAndLeaveCriticalRegion",
    "RtlPinAtomInAtomTable",
    "RtlCreateHeap",
    "ObReferenceObjectByPointer",
    "ZwCreateDirectoryObject",
    "ObInsertObject",
    "ZwOpenDirectoryObject",
    "ZwQueryDirectoryObject",
    "PsGetProcessWin32WindowStation",
    "PsSetProcessWindowStation",
    "RtlDestroyAtomTable",
    "RtlImageNtHeader",
    "ZwQuerySystemInformation",
    "ExAllocatePoolWithQuotaTag",
    "ExfAcquirePushLockExclusive",
    "ExfTryToWakePushLock",
    "ZwQueryKey",
    "ZwQueryObject",
    "ZwQueryDirectoryFile",
    "ExAllocatePool",
    "MmHighestUserAddress",
    "RtlNumberOfSetBits",
    "RtlTestBit",
    "RtlTimeToTimeFields",
    "ExSystemTimeToLocalTime",
    "RtlUnwindEx",
    "RtlUpcaseUnicodeChar",
    "RtlAnsiCharToUnicodeChar",
    "PsProcessType",
    "ZwQueryInformationFile",
    "ZwUnmapViewOfSection",
    "ZwMapViewOfSection",
    "ZwCreateFile",
    "IoGetCurrentProcess",
    "RtlImageDirectoryEntryToData",
    "ZwSetSystemInformation",
    "RtlCopyUnicodeString",
    "RtlAppendUnicodeToString",
    "RtlNtStatusToDosError",
    "IoSynchronousInvalidateDeviceRelations",
    "ZwClose",
    "ExFreePool",
    "IoOpenDeviceRegistryKey",
    "IoGetRelatedDeviceObject",
    "IoGetDeviceObjectPointer",
    "IofCallDriver",
    "IoBuildSynchronousFsdRequest",
    "IoBuildDeviceIoControlRequest",
    "RtlQueryRegistryValues",
    "RtlEqualUnicodeString",
    "RtlInitUnicodeString",
    "vDbgPrintExWithPrefix",
    "PsGetCurrentProcessWin32Process",
    "KePulseEvent",
    "ObReferenceObjectByHandle",
    "ObfDereferenceObject",
    "KeWaitForSingleObject",
    "KeSetEvent",
    "KeReadStateEvent",
    "KeClearEvent",
    "KeInitializeEvent",
    "ProbeForRead",
    "ExFreePoolWithTag",
    "ExAllocatePoolWithTag",
    "KeUnstackDetachProcess",
    "DbgPrint",
    "ExEventObjectType",
    "NlsMbCodePageTag",
    "PsThreadType",
];

pub const WIN32K_HAL_IMPORTS: &[&str] = &["KeQueryPerformanceCounter"];

pub const WIN32K_FTFD_IMPORTS: &[&str] = &[
    "FT_Done_Library",
    "FT_GlyphSlot_Oblique",
    "FT_GlyphSlot_Embolden",
    "FT_Get_Sfnt_Name",
    "FT_Get_Sfnt_Name_Count",
    "FT_Get_WinFNT_Header",
    "FT_Outline_Get_Bitmap",
    "FT_Outline_Transform",
    "FT_Outline_Translate",
    "FT_Bitmap_Done",
    "FT_Bitmap_Convert_ReactOS_Hack",
    "FT_Bitmap_New",
    "FT_Vector_Unit",
    "FT_Load_Sfnt_Table",
    "FT_Get_Sfnt_Table",
    "FT_Get_PS_Font_Info",
    "FT_Matrix_Multiply",
    "FT_Done_Glyph",
    "FT_Glyph_To_Bitmap",
    "FT_Get_Glyph",
    "FT_Vector_Transform",
    "FT_MulFix",
    "FT_MulDiv",
    "FT_Get_Next_Char",
    "FT_Get_First_Char",
    "FT_Get_Char_Index",
    "FT_Set_Charmap",
    "FT_Get_Kerning",
    "FT_Set_Transform",
    "FT_Load_Glyph",
    "FT_Request_Size",
    "FT_Done_Face",
    "FT_New_Memory_Face",
    "FT_Init_FreeType",
];
